# Member.destroy_all
# Event.destroy_all
# EventMember.destroy_all
# Whiskey.destroy_all
# Comment.destroy_all

Member.create(first_name:"Andy", last_name:"Rackaskaus", email:"andrewrackauskas@yahoo.com", password: "testpass")
Member.create(first_name:"Ben", last_name:"Davis", email:"benjaminedavis@gmail.com", password: "testpass")
Member.create(first_name:"Keith", last_name:"Wilson", email:"kwilsinca@gmail.com ", password: "testpass")
Member.create(first_name:"Kevin", last_name:"Robie", email:"kevinr@robiedesign.com", password: "testpass")
Member.create(first_name:"Matt", last_name:"Granger", email:"grangerdanger@earthlink.net", password: "testpass")
Member.create(first_name:"Robert", last_name:"Granger", email:"robertgranger@yahoo.com", password: "testpass")
Member.create(first_name:"Al", last_name:"Lagrosa", email:"re_al_80@yahoo.com", password: "testpass")
Member.create(first_name:"James", last_name:"Chen", email:"james.chen@13east.com ", password: "testpass")
Member.create(first_name:"Paul", last_name:"Moore", email:"paulrmoore@sbcglobal.net", password: "testpass")
Member.create(first_name:"Kirk", last_name:"Duncan", email:"kirk0605@yahoo.com", password: "testpass")
Member.create(first_name:"Brian", last_name:"Gibney", email:"brianggibney@gmail.com ", password: "testpass")
Member.create(first_name:"Dan", last_name:"Choi", email:"dc@gmail.com", password: "testpass")
Member.create(first_name:"David", last_name:"Ivy", email:"di@gmail.com", password: "testpass")
Member.create(first_name:"Mike", last_name:"Roth", email:"mr@gmail.com", password: "testpass")
Member.create(first_name:"Ron", last_name:"Simms", email:"rs@gmail.com", password: "testpass")
Member.create(first_name:"Mike", last_name:"Ochs", email:"mo@gmail.com", password: "testpass")
Member.create(first_name:"Johnny", last_name:"Tu", email:"johnnyt@pacificwestlitho.com", password: "testpass")
Member.create(first_name:"John", last_name:"McLean", email:"jm@gmail.com", password: "testpass")
Member.create(first_name:"Ed", last_name:"Vigdor", email:"ev@gmail.com", password: "testpass")
Member.create(first_name:"Brian", last_name:"Patrick", email:"brianpatrickw@gmail.com", password: "testpass")

Event.create(date:"05/20/06", host: "Andy Rackaskaus", theme: "The Inception!", description: "Single Malt Scotch")
Event.create(date:"07/15/06", host: "Kevin Robie", description: "Single Malt Scotch")
Event.create(date:"11/11/06", host: "Andy Rackaskaus", description: "Single Malt Scotch")
Event.create(date:"03/17/07", host: "Andy Rackaskaus", theme: "St. Patrick's Day!", description: "Irish Whiskey")
Event.create(date:"06/09/07", host: "Andy Rackaskaus", description: "Single Malt Scotch")
Event.create(date:"09/20/08", host: "Kevin Robie", description: "Single Malt Scotch")
Event.create(date:"02/28/09", host: "Andy Rackaskaus", description: "Single Malt Scotch")
Event.create(date:"05/09/09", host: "John McLean", description: "Single Malt Scotch")
Event.create(date:"09/26/09", host: "Brian Walsh", description: "Single Malt Scotch")
Event.create(date:"02/20/10", host: "Andy Rackaskaus", theme: "President's Day!", description: "American Whiskey")
Event.create(date:"10/22/11", host: "Andy Rackaskaus", description: "Single Malt Scotch")
Event.create(date:"02/19/12", host: "Andy Rackaskaus", description: "Single Malt Scotch")
Event.create(date:"07/28/12", host: "Andy Rackaskaus", theme: "American Whiskey!", description: "American Whiskey")
Event.create(date:"04/13/13", host: "Andy Rackaskaus", description: "Single Malt Scotch")
Event.create(date:"07/14/13", host: "Andy Rackaskaus", description: "Single Malt Scotch")
Event.create(date:"11/02/13", host: "Andy Rackaskaus", theme: "Free For All!", description: "All Whiskey Types")
Event.create(date:"01/25/14", host: "Andy Rackaskaus", theme: "Free For All!", description: "All Whiskey Types")
Event.create(date:"04/25/15", host: "Andy Rackaskaus", theme: "Free For All!", description: "All Whiskey Types")

EventMember.create(event_id: 1, member_id: 1, attended: true)
EventMember.create(event_id: 1, member_id: 2, attended: true)
EventMember.create(event_id: 1, member_id: 3, attended: true)
EventMember.create(event_id: 1, member_id: 4, attended: true)
EventMember.create(event_id: 1, member_id: 5, attended: true)
EventMember.create(event_id: 1, member_id: 6, attended: true)
EventMember.create(event_id: 1, member_id: 9, attended: true)
EventMember.create(event_id: 1, member_id: 13, attended: true)

EventMember.create(event_id: 2, member_id: 1, attended: true)
EventMember.create(event_id: 2, member_id: 2, attended: true)
EventMember.create(event_id: 2, member_id: 3, attended: true)
EventMember.create(event_id: 2, member_id: 4, attended: true)
EventMember.create(event_id: 2, member_id: 6, attended: true)
EventMember.create(event_id: 2, member_id: 9, attended: true)
EventMember.create(event_id: 2, member_id: 13, attended: true)
EventMember.create(event_id: 2, member_id: 15, attended: true)

EventMember.create(event_id: 3, member_id: 1, attended: true)
EventMember.create(event_id: 3, member_id: 2, attended: true)
EventMember.create(event_id: 3, member_id: 3, attended: true)
EventMember.create(event_id: 3, member_id: 4, attended: true)
EventMember.create(event_id: 3, member_id: 5, attended: true)
EventMember.create(event_id: 3, member_id: 6, attended: true)
EventMember.create(event_id: 3, member_id: 9, attended: true)
EventMember.create(event_id: 3, member_id: 13, attended: true)

EventMember.create(event_id: 4, member_id: 1, attended: true)
EventMember.create(event_id: 4, member_id: 3, attended: true)
EventMember.create(event_id: 4, member_id: 4, attended: true)
EventMember.create(event_id: 4, member_id: 7, attended: true)
EventMember.create(event_id: 4, member_id: 9, attended: true)

EventMember.create(event_id: 5, member_id: 1, attended: true)
EventMember.create(event_id: 5, member_id: 3, attended: true)
EventMember.create(event_id: 5, member_id: 4, attended: true)
EventMember.create(event_id: 5, member_id: 5, attended: true)
EventMember.create(event_id: 5, member_id: 6, attended: true)
EventMember.create(event_id: 5, member_id: 13, attended: true)

EventMember.create(event_id: 6, member_id: 1, attended: true)
EventMember.create(event_id: 6, member_id: 2, attended: true)
EventMember.create(event_id: 6, member_id: 4, attended: true)
EventMember.create(event_id: 6, member_id: 9, attended: true)
EventMember.create(event_id: 6, member_id: 18, attended: true)
EventMember.create(event_id: 6, member_id: 19, attended: true)

EventMember.create(event_id: 7, member_id: 1, attended: true)
EventMember.create(event_id: 7, member_id: 2, attended: true)
EventMember.create(event_id: 7, member_id: 3, attended: true)
EventMember.create(event_id: 7, member_id: 4, attended: true)
EventMember.create(event_id: 7, member_id: 6, attended: true)
EventMember.create(event_id: 7, member_id: 9, attended: true)
EventMember.create(event_id: 7, member_id: 11, attended: true)

EventMember.create(event_id: 8, member_id: 1, attended: true)
EventMember.create(event_id: 8, member_id: 2, attended: true)
EventMember.create(event_id: 8, member_id: 5, attended: true)
EventMember.create(event_id: 8, member_id: 6, attended: true)
EventMember.create(event_id: 8, member_id: 9, attended: true)
EventMember.create(event_id: 8, member_id: 20, attended: true)

EventMember.create(event_id: 9, member_id: 1, attended: true)
EventMember.create(event_id: 9, member_id: 2, attended: true)
EventMember.create(event_id: 9, member_id: 6, attended: true)
EventMember.create(event_id: 9, member_id: 9, attended: true)
EventMember.create(event_id: 9, member_id: 16, attended: true)
EventMember.create(event_id: 9, member_id: 18, attended: true)

EventMember.create(event_id: 10, member_id: 1, attended: true)
EventMember.create(event_id: 10, member_id: 3, attended: true)
EventMember.create(event_id: 10, member_id: 5, attended: true)
EventMember.create(event_id: 10, member_id: 14, attended: true)

EventMember.create(event_id: 11, member_id: 1, attended: true)
EventMember.create(event_id: 11, member_id: 2, attended: true)
EventMember.create(event_id: 11, member_id: 3, attended: true)
EventMember.create(event_id: 11, member_id: 6, attended: true)
EventMember.create(event_id: 11, member_id: 7, attended: true)

EventMember.create(event_id: 12, member_id: 1, attended: true)
EventMember.create(event_id: 12, member_id: 2, attended: true)
EventMember.create(event_id: 12, member_id: 3, attended: true)
EventMember.create(event_id: 12, member_id: 4, attended: true)
EventMember.create(event_id: 12, member_id: 6, attended: true)
EventMember.create(event_id: 12, member_id: 7, attended: true)
EventMember.create(event_id: 12, member_id: 9, attended: true)
EventMember.create(event_id: 12, member_id: 10, attended: true)

EventMember.create(event_id: 13, member_id: 1, attended: true)
EventMember.create(event_id: 13, member_id: 2, attended: true)
EventMember.create(event_id: 13, member_id: 7, attended: true)
EventMember.create(event_id: 13, member_id: 9, attended: true)

EventMember.create(event_id: 14, member_id: 1, attended: true)
EventMember.create(event_id: 14, member_id: 2, attended: true)

EventMember.create(event_id: 15, member_id: 1, attended: true)
EventMember.create(event_id: 15, member_id: 7, attended: true)

EventMember.create(event_id: 16, member_id: 1, attended: true)
EventMember.create(event_id: 16, member_id: 2, attended: true)
EventMember.create(event_id: 16, member_id: 3, attended: true)
EventMember.create(event_id: 16, member_id: 4, attended: true)
EventMember.create(event_id: 16, member_id: 6, attended: true)
EventMember.create(event_id: 16, member_id: 7, attended: true)
EventMember.create(event_id: 16, member_id: 8, attended: true)
EventMember.create(event_id: 16, member_id: 12, attended: true)

EventMember.create(event_id: 17, member_id: 1, attended: true)
EventMember.create(event_id: 17, member_id: 3, attended: true)
EventMember.create(event_id: 17, member_id: 5, attended: true)
EventMember.create(event_id: 17, member_id: 6, attended: true)
EventMember.create(event_id: 17, member_id: 7, attended: true)
EventMember.create(event_id: 17, member_id: 8, attended: true)
EventMember.create(event_id: 17, member_id: 10, attended: true)

EventMember.create(event_id: 18, member_id: 1, attended: true)
EventMember.create(event_id: 18, member_id: 2, attended: true)
EventMember.create(event_id: 18, member_id: 8, attended: true)
EventMember.create(event_id: 18, member_id: 17, attended: true)





Comment.create(member_id: 1, whiskey_id: 1, comment: "burn, orange, water +")
Comment.create(member_id: 1, whiskey_id: 2, comment: "vanilla, smooth")
Comment.create(member_id: 1, whiskey_id: 3, comment: "maple, pepper finish")
Comment.create(member_id: 1, whiskey_id: 4, comment: "burn, salty")
Comment.create(member_id: 1, whiskey_id: 4, comment: "sweet smooth")
Comment.create(member_id: 1, whiskey_id: 5, comment: "smooth")
Comment.create(member_id: 1, whiskey_id: 6, comment: "seaweed, smoke")
Comment.create(member_id: 1, whiskey_id: 7, comment: "smokey, bbq, musky")
Comment.create(member_id: 1, whiskey_id: 8, comment: "Bushmills-y, water +")
Comment.create(member_id: 1, whiskey_id: 9, comment: "young, slight peat, water -")
Comment.create(member_id: 1, whiskey_id: 10, comment: "oomph, water +")
Comment.create(member_id: 1, whiskey_id: 11, comment: "spicy sweet, smooth w/ water")
Comment.create(member_id: 1, whiskey_id: 12, comment: "bite, floral, water +")
Comment.create(member_id: 1, whiskey_id: 13, comment: "everyday")
Comment.create(member_id: 1, whiskey_id: 14, comment: "salt, smoke, peat")
Comment.create(member_id: 1, whiskey_id: 15, comment: "honey, floral, water +")
Comment.create(member_id: 1, whiskey_id: 16, comment: "peat, smoke, water -")
Comment.create(member_id: 1, whiskey_id: 17, comment: "seaweed")
Comment.create(member_id: 1, whiskey_id: 18, comment: "seaweed, seagulls nuts, water -")
Comment.create(member_id: 1, whiskey_id: 19, comment: "smooth, water +")
Comment.create(member_id: 1, whiskey_id: 20, comment: "fire, robust, smokey, water +")
Comment.create(member_id: 1, whiskey_id: 21, comment: "potent beast, walty, fire, water +")
Comment.create(member_id: 1, whiskey_id: 22, comment: "flowery")
Comment.create(member_id: 1, whiskey_id: 23, comment: "orange, water +")
Comment.create(member_id: 1, whiskey_id: 24, comment: "bite, floral, water ++")
Comment.create(member_id: 1, whiskey_id: 25, comment: "cigar, burn, peaty")
Comment.create(member_id: 1, whiskey_id: 26, comment: "honey, sweet burn, water +")
Comment.create(member_id: 1, whiskey_id: 27, comment: "water +, flavorful")
Comment.create(member_id: 1, whiskey_id: 28, comment: "water +, honey")
Comment.create(member_id: 1, whiskey_id: 29, comment: "scotch-y, salty, nutty")
Comment.create(member_id: 1, whiskey_id: 29, comment: "spice kick, water +")
Comment.create(member_id: 1, whiskey_id: 29, comment: "smooth, water -")
Comment.create(member_id: 1, whiskey_id: 30, comment: "smokey")
Comment.create(member_id: 1, whiskey_id: 31, comment: "daily drink")
Comment.create(member_id: 1, whiskey_id: 32, comment: "did not cut")
Comment.create(member_id: 1, whiskey_id: 33, comment: "daily drink, pepper")
Comment.create(member_id: 1, whiskey_id: 34, comment: "water +")
Comment.create(member_id: 1, whiskey_id: 35, comment: "water ++")
Comment.create(member_id: 1, whiskey_id: 35, comment: "cigar +")
Comment.create(member_id: 1, whiskey_id: 42, comment: "fiery, smokey, peaty, salty")
Comment.create(member_id: 1, whiskey_id: 43, comment: "bite, water +")
Comment.create(member_id: 1, whiskey_id: 44, comment: "summer, water +")
Comment.create(member_id: 1, whiskey_id: 45, comment: "seems mild for Lagavulin")
Comment.create(member_id: 1, whiskey_id: 46, comment: "smooth, water +, citrus")
Comment.create(member_id: 1, whiskey_id: 47, comment: "pepper kick, water ++")
Comment.create(member_id: 1, whiskey_id: 48, comment: "holy crapa, I'm drinkin' scapa, sea")
Comment.create(member_id: 1, whiskey_id: 49, comment: "smooth")
Comment.create(member_id: 1, whiskey_id: 50, comment: "water -, caramel")
Comment.create(member_id: 1, whiskey_id: 51, comment: "salty")
Comment.create(member_id: 1, whiskey_id: 52, comment: "peatier than 12")
Comment.create(member_id: 1, whiskey_id: 52, comment: "smooth for Islay")
Comment.create(member_id: 1, whiskey_id: 53, comment: "water -, spicy")
Comment.create(member_id: 1, whiskey_id: 54, comment: "Scotch, need to acquire, water +")
Comment.create(member_id: 1, whiskey_id: 55, comment: "smooth")
Comment.create(member_id: 1, whiskey_id: 55, comment: "water ++, light sweetness, mellow nose")
Comment.create(member_id: 1, whiskey_id: 56, comment: "****bottle watered in error/ OMIT*****")
Comment.create(member_id: 1, whiskey_id: 57, comment: "water +, dry, Scotch")
Comment.create(member_id: 1, whiskey_id: 58, comment: "Scotch, need to acquire, water +")
Comment.create(member_id: 1, whiskey_id: 59, comment: "mellower than the 10")
Comment.create(member_id: 1, whiskey_id: 60, comment: "seaweed, smoke")
Comment.create(member_id: 1, whiskey_id: 61, comment: "water -, Chardonnay-like, clean")
Comment.create(member_id: 1, whiskey_id: 62, comment: "unchill blend (16yr + 6yr), sweet, afterburn")
Comment.create(member_id: 1, whiskey_id: 63, comment: "too mellow, sweet")
Comment.create(member_id: 1, whiskey_id: 64, comment: "sweet, smooth, light burn aftershock")
Comment.create(member_id: 1, whiskey_id: 65, comment: "smokey, peaty, salty, earthy, sherry cask")
Comment.create(member_id: 1, whiskey_id: 66, comment: "sweet, light, vanilla notes, caramel")
Comment.create(member_id: 1, whiskey_id: 67, comment: "1 sherry, 2 bourbon, 2 bordeaux casks, peat, mild sweet/honey ****")
Comment.create(member_id: 1, whiskey_id: 68, comment: "peppery, crisp, slight burn, A-cup w/ water")
Comment.create(member_id: 1, whiskey_id: 69, comment: "peat bomb, buttery, mild salt, Tyson one trick punch, unexpectedly pleasant")
Comment.create(member_id: 1, whiskey_id: 70, comment: "less peaty, smoke, water -")
Comment.create(member_id: 1, whiskey_id: 71, comment: "highlands, heavily peated, sea, cinnamon")
Comment.create(member_id: 1, whiskey_id: 72, comment: "bite, salty, smooth, less complex than Ardbeg Alligator")
Comment.create(member_id: 1, whiskey_id: 73, comment: "burn, bright, no peat, quick, smoky finish")
Comment.create(member_id: 1, whiskey_id: 74, comment: "smoke, peat")
Comment.create(member_id: 1, whiskey_id: 75, comment: "super pear, easy , pleasant, smooth, light")
Comment.create(member_id: 1, whiskey_id: 76, comment: "peat ass-kicker, nutty")
Comment.create(member_id: 1, whiskey_id: 76, comment: "The standard")
Comment.create(member_id: 1, whiskey_id: 77, comment: "nose burn, sea, milder than 10, iodine")
Comment.create(member_id: 1, whiskey_id: 78, comment: "mild rose, burn, seaweed, brine, sharp")
Comment.create(member_id: 1, whiskey_id: 78, comment: "light peat, bite, brine")
Comment.create(member_id: 1, whiskey_id: 79, comment: "clean, crisp, sweet, vanilla, white wine")
Comment.create(member_id: 1, whiskey_id: 79, comment: "hot nose, good burn, rose essence, smooth")
Comment.create(member_id: 1, whiskey_id: 80, comment: "sweet burn, spicy, ice +")
Comment.create(member_id: 1, whiskey_id: 80, comment: "very corn-y in smell and taste, unique, full-bodied, no burn, musky")
Comment.create(member_id: 1, whiskey_id: 81, comment: "smooth like Irish Whisky (Jameson -like), caramel, honey")
Comment.create(member_id: 1, whiskey_id: 82, comment: "nose hot, burns, ice +, everyday, nothing special")
Comment.create(member_id: 1, whiskey_id: 83, comment: "Distillery only, burn nose, exceptional, hot, water +, ice+, neat +")
Comment.create(member_id: 1, whiskey_id: 84, comment: "smoky, peaty, salty, super smoke")
Comment.create(member_id: 1, whiskey_id: 85, comment: "smells hot, clean, light smoke & peat, YOUNG")
Comment.create(member_id: 1, whiskey_id: 86, comment: "spicy, hot, alcohol forward, green apple hints,  water + - STRONG!")
Comment.create(member_id: 1, whiskey_id: 87, comment: "Bourbon is profound, sweet, mild, low peat")
Comment.create(member_id: 1, whiskey_id: 87, comment: "smells of the sea, spicy bite, ild smokiness, peat forward, deep, should be mellow but it's not")
Comment.create(member_id: 1, whiskey_id: 88, comment: "buttery, smooth, mellow, orange, milder than the nose")
Comment.create(member_id: 1, whiskey_id: 89, comment: "oakiness, heavy, molasses, frisky, bite")
Comment.create(member_id: 1, whiskey_id: 90, comment: "post wood finish, sweet, not woody")
Comment.create(member_id: 1, whiskey_id: 91, comment: "non-chill filtered, hot nose, campfire, sweet finish, chocolate")
Comment.create(member_id: 1, whiskey_id: 92, comment: "mellow, woody, mild afterburn, daily…")
Comment.create(member_id: 1, whiskey_id: 93, comment: "mild peat, lemon/apple hints, chardonnay/muscat, smooth, sweet, buttery")
Comment.create(member_id: 1, whiskey_id: 94, comment: "peat ehaven, not super smoky, vatted, pleasant, vibrant, briny, This is why I drink whisky - RG")
Comment.create(member_id: 1, whiskey_id: 95, comment: "nose f-ing heavenly, mild, sweet, silkysmooth")
Comment.create(member_id: 1, whiskey_id: 96, comment: "Oban-esque, burn, fruit forward, biny nose")
Comment.create(member_id: 1, whiskey_id: 97, comment: "dark, barrel wood char, hot, spice")
Comment.create(member_id: 1, whiskey_id: 98, comment: "hot nose, mild, rye-ish, sweet, vanilla")
Comment.create(member_id: 1, whiskey_id: 99, comment: "Rye-Bourbon-Scotch blend, smoky, sweet, briny, smoke dissapates quickly")
Comment.create(member_id: 1, whiskey_id: 100, comment: "hot nose, Bardstown, sweet, caramel, Bourbon")
Comment.create(member_id: 1, whiskey_id: 101, comment: "non-descript, thin")
Comment.create(member_id: 1, whiskey_id: 102, comment: "hot nose, peat, brine")
Comment.create(member_id: 1, whiskey_id: 103, comment: "Bourbon cask, Petrus Cask, bottled at Bruichladdich, caramel, mellow raisin")
Comment.create(member_id: 1, whiskey_id: 104, comment: "Cask Strength Unchillfiltered, smells of ocean, hot, peat, smoke, almond")
Comment.create(member_id: 1, whiskey_id: 105, comment: "peat ass-kicker, nutty")
Comment.create(member_id: 1, whiskey_id: 106, comment: "2nd tasting, hot nose, peat, brine")
Comment.create(member_id: 1, whiskey_id: 107, comment: "creamy, super smooth, buttery, oaky, butterscotch, hot nose, caramel")
Comment.create(member_id: 1, whiskey_id: 108, comment: "maturedin Hogshead, spicy, not nose, alochol-y, raisin")
Comment.create(member_id: 1, whiskey_id: 109, comment: "caramel, smooth, the standard")
Comment.create(member_id: 1, whiskey_id: 110, comment: "tasty nose, caramel, toffee, smooth, dry, not brine-y, sweet, citrus, waxy")
Comment.create(member_id: 1, whiskey_id: 111, comment: "Bardstown, sweet nose, sweet heat, a bite")
Comment.create(member_id: 1, whiskey_id: 111, comment: "wheat (Makers-ish), not not, sweet, easy drinking everyday")
Comment.create(member_id: 1, whiskey_id: 112, comment: "light heat on nose, spice, complex")
Comment.create(member_id: 1, whiskey_id: 113, comment: "sweet corn, light charcoal, leather smell.  Rye & Bourbon blend")
Comment.create(member_id: 1, whiskey_id: 114, comment: "Non Chill Filtered, clean, not hot, earthiness, it's own beast")
Comment.create(member_id: 1, whiskey_id: 115, comment: "Island malt, double matured in amoruso oak, bbq, smoke")
Comment.create(member_id: 1, whiskey_id: 116, comment: "disappointingly mild, Oban-like, lacks complexity, far from stormy")
Comment.create(member_id: 1, whiskey_id: 117, comment: "Super Mild, a little too much so, good mixer")
